# These are supported funding model platforms

github: [hexodus-project]
patreon: hexodus
open_collective: hexodus
ko_fi: hexodus
tidelift: 
community_bridge:
liberapay:
issuehunt:
otechie:
custom: ['https://paypal.me/hexodusproject', 'https://buymeacoffee.com/hexodus']