#!/bin/sh

#
# Copyright © 2015-present The Gradle Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, try setting SHELL before running this script: e.g.
#       SHELL=/bin/bash ./gradlew
#
#   (2) All environment variables ending with _JVM_OPTS are considered
#       as JVM options for the Gradle process. For example:
#       export GRADLE_OPTS="-XX:+AggressiveOpts"
#       export JAVA_OPTS="-Xmx2048m"
#       export ORG_GRADLE_PROJECT_opts="-Xmx1024m"
#       export ORG_GRADLE_PROJECT_test_jvm_args="-Xmx512m"
#       All of them are applied to the Gradle process.
#
#   Important for customization:
#
#   (1) You can use any of the *_OPTS variables to include command line
#       arguments for this script, e.g. to add JVM options for the Gradle
#       process, you can set the GRADLE_OPTS environment variable:
#       export GRADLE_OPTS="-Xmx2048m"
#
#   (2) The script will create a JVM options file named ".gradle.jvmopts"
#       in the current directory. This will be used to store all JVM options
#       passed to the script. This is useful when you want to customize the
#       JVM options for a specific project without setting environment
#       variables.
#
#   (3) If you need to set JVM options for a specific Gradle user, you can
#       create a file named "gradle.jvmopts" in your Gradle user home
#       directory (default: ~/.gradle). This will be used to store all JVM
#       options passed to the script for that specific user.
#
#   (4) You can use the GRADLE_EXIT_CONSOLE environment variable to keep
#       the console open after the script has finished.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25783)
APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit: $MAX_FD" >&2
        if [ $? -eq 0 ] && [ "$MAX_FD" != unlimited ] ; then
            # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
            # shellcheck disable=SC2039
            ulimit -n $MAX_FD ||
                warn "Could not set maximum file descriptor limit: $MAX_FD" >&2
        fi
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * all jvm arguments
#   * -server
#   * APP_JVM_OPTS
#   * JAVA_OPTS
#   * GRADLE_OPTS
#   * environment variables ending in _JVM_OPTS

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )
    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: a `for` loop captures its iteration list before it begins, so
        # changing the positional parameters inside the loop will not affect
        # the number of iterations!
        shift                   # remove old arg
        set -- "$@" "$arg"      # push replacement arg
    done
fi

# Collect all arguments for the java command:
#   * Add JVM arguments and GRADLE_OPTS (environment variables) to the "options" queue
#   * Add the main class name to the "options" queue
#   * Add the classpath to the "options" queue
#   * Add the main arguments to the "args" queue
#   * Add the remaining arguments from the command line to the "args" queue
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

exec "$JAVACMD" "$@"