name: Bug Report
about: Create a report to help us improve
title: '[Bug] '
labels: bug
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happens instead of the expected behavior
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: input
    id: device
    attributes:
      label: Device
      placeholder: Samsung Z Flip 5, etc.
    validations:
      required: true
  - type: input
    id: android-version
    attributes:
      label: Android Version
      placeholder: Android 16 (One UI 8), etc.
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: App Version
      placeholder: 1.0.0, etc.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.